spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5432/
    password: 
    username:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
command:
  line-runner: true
  jwt-key: secretKey
  expire-time: 172800000
